const masterWordList = {
  word: [
    "A",
    "big",
    "cat",
    "jumped",
    "quickly",
    "over",
    "the",
    "lazy",
    "dog",
    "big",
    "cat",
    "jumped",
    "quickly",
    "over",
    "the",
    "lazy",
    "dog",
    "big",
    "cat",
    "jumped",
    "quickly",
    "over",
    "the",
    "lazy",
    "dog",
  ],
  bird: ["parrot", "sparrow", "eagle", "owl", "pigeon", "duck", "peacock"],
  animal: ["cat", "dog", "elephant", "goat", "lion", "rat"],
  fruit: ["apple", "banana", "orange", "grape", "mango", "pineapple"],
  object: ["pen", "hat", "jug", "net", "tree", "bottle", "chair"],
};
